### ISSUE TITLE
SVExDB Lite Format?

### ISSUE THREAD

**Issue by leone-pisces** [Cu3PO42/SVExDB-Lite#2]
I'm 100% new to this program and I was wondering how to plug information into it. I also have no idea what data is relevant to the program. I would really appreciate some pointers.

**Comment by Cu3PO42** [comment]
You would take the output of a tool like KeySAVe, for example. The only thing that is required of the input is that it contains exactly 4 consecutive digits somewhere in every line—that is assumed to be the TSV. Everything else is optional. The following would be valid input:

ˋˋˋ
1234
4095
0001
ˋˋˋ

But so would

ˋˋˋ
Bulbasaur [0001]
Squirtle [0002]
Charmander [0003]
ˋˋˋ

**Comment by leone-pisces** [comment]
So again since I'm new at this, how would I get a data file from my Ultra Sun game to the KeySAVe program? Are there any other programs I could use to accomplish this?

**Comment by Cu3PO42** [comment]
Oh, I figured you were just new to the website, not SV hatching in general. You can find all information about KeySAVe, including how to get your data in there, in the [documentation](https://cu3po42.gitbooks.io/keysave/content/). If you can’t use any of the methods you can ask for help on the daily thread on r/SVExchange.

**Comment by leone-pisces** [comment]
Alright thanks so much I really appreciate it.
