### ISSUE TITLE
Currently Not Working?

### ISSUE THREAD

**Issue by kimbekaw** [Cu3PO42/SVExDB-Lite#3]
Hi there!

I just went to check this awesome tool out, but it doesn't seem to be working. I've included a screenshot of some examples I tried and also marked the TSVs that should match. The TSVs without attached data are mines and both have current threads, so should work in theory. 

I'm using Google Chrome Version 65.0.3325.181 (Official Build) (64-bit) and have turned off any ad blockers, etc. 

![notworking](https://user-images.githubusercontent.com/7297371/38546743-523d3c10-3c62-11e8-8cee-425ee4a52592.PNG)

**Comment by Cu3PO42** [comment]
Hi!

Thanks for letting me know and the nice issue report!
I can confirm the problem, it appears something has broken my SVEx Crawler, I'm looking into it!

**Comment by Cu3PO42** [comment]
I've tracked down the issue to [this API change](https://www.reddit.com/r/redditdev/comments/87wwl8/reddit_appears_to_have_slightly_changed_how_the/) by Reddit, which they helpfully didn't announce. *mumbles*

Any way, I have adapted the crawler and everything is back to working order!
